# Generated by Django 3.0.5 on 2020-05-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graveyard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decedent',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='decedent',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='middle name'),
        ),
    ]
